version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2022-10-15T19-57-03Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_storage:/data
    command: server --console-address ":9001" /data
    env_file: .env
    restart: always