# Generated by Django 5.1.1 on 2024-09-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('active', 'Действует'), ('deleted', 'Удален')], default='active', max_length=7, verbose_name='Статус')),
                ('url', models.URLField(verbose_name='URL')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
            },
        ),
        migrations.AlterModelOptions(
            name='mymodel',
            options={'verbose_name': 'Моя модель', 'verbose_name_plural': 'Мои модели'},
        ),
    ]
