# Generated by Django 5.1.1 on 2024-09-22 17:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_spare_alter_mymodel_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('d_start', models.DateTimeField(default=datetime.datetime(2024, 9, 22, 17, 37, 28, 778184, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('d_form', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('d_compl', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('adminer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('creater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Order_Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('id_order_mm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
            options={
                'verbose_name': 'Заказ-Запчасть',
                'verbose_name_plural': 'Заказы-Запчасти',
                'db_table': 'Order_Spare',
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RenameField(
            model_name='spare',
            old_name='id',
            new_name='id_spare',
        ),
        migrations.RenameField(
            model_name='spare',
            old_name='name',
            new_name='name_spare',
        ),
        migrations.RenameField(
            model_name='spare',
            old_name='price',
            new_name='price_spare',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='description',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='status',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='url',
        ),
        migrations.AddField(
            model_name='spare',
            name='description_spare',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='spare',
            name='status_spare',
            field=models.IntegerField(choices=[(0, 'Действует'), (1, 'Удален')], default=0, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='spare',
            name='url_spare',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterModelTable(
            name='spare',
            table='Spare',
        ),
        migrations.AddField(
            model_name='order_spare',
            name='id_spare_mm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.spare'),
        ),
        migrations.AlterUniqueTogether(
            name='order_spare',
            unique_together={('id_order_mm', 'id_spare_mm')},
        ),
    ]
