# Generated by Django 5.1.1 on 2024-09-22 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_order_spare_delete_mymodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='d_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 17, 47, 11, 579541, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
