# Generated by Django 5.1.1 on 2024-09-22 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_d_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'Удален'), (2, 'Сформирован'), (3, 'Завершен'), (4, 'Отклонен')], default=0, max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='d_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 18, 16, 20, 603825, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
