# Generated by Django 5.1.1 on 2024-09-24 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_d_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='d_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 5, 18, 59, 701176, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
